export const MOCK_PRODUCTS = [
    {
        id: '1',
        slug: 'classic-heavy-cotton-tshirt',
        nameKey: 'prod_t_shirt',
        descriptionKey: 'prod_t_shirt_desc',
        price: 29.99,
        imageSrc: '/images/products/classic-tshirt.png',
        images: ['/images/products/classic-tshirt.png', '/images/categories/t-shirts.png'],
        categoryKey: 'T-Shirts',
        createdAt: '2024-01-01',
        minimumOrder: 10,
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
    },
    {
        id: '2',
        slug: 'premium-pullover-hoodie',
        nameKey: 'prod_hoodie',
        descriptionKey: 'prod_hoodie_desc',
        price: 59.99,
        imageSrc: '/images/products/premium-hoodie.png',
        images: ['/images/products/premium-hoodie.png', '/images/categories/sweatshirts.png'],
        categoryKey: 'Sweatshirts',
        createdAt: '2024-01-05',
        minimumOrder: 5,
        sizes: ['S', 'M', 'L', 'XL', 'XXL']
    },
    {
        id: '3',
        slug: 'custom-ceramic-mug',
        nameKey: 'prod_mug',
        descriptionKey: 'prod_mug_desc',
        price: 14.99,
        imageSrc: '/images/products/ceramic-mug.png',
        images: ['/images/products/ceramic-mug.png', '/images/categories/drinkware.png'],
        categoryKey: 'Drinkware',
        createdAt: '2024-01-10',
        minimumOrder: 24,
        sizes: []
    },
    {
        id: '4',
        slug: 'eco-friendly-tote-bag',
        nameKey: 'prod_tote',
        descriptionKey: 'prod_tote_desc',
        price: 19.99,
        imageSrc: '/images/products/eco-tote.png',
        images: ['/images/products/eco-tote.png', '/images/categories/bags.png'],
        categoryKey: 'Bags',
        createdAt: '2024-02-01',
        minimumOrder: 50,
        sizes: ['One Size']
    },
    {
        id: '5',
        slug: 'stainless-steel-tumbler',
        nameKey: 'prod_tumbler',
        descriptionKey: 'prod_tumbler_desc',
        price: 34.99,
        imageSrc: '/images/products/stainless-tumbler.png',
        images: ['/images/products/stainless-tumbler.png', '/images/categories/drinkware.png'],
        categoryKey: 'Drinkware',
        createdAt: '2024-02-15',
        minimumOrder: 12,
        sizes: []
    },
    {
        id: '6',
        slug: 'vintage-tshirt',
        nameKey: 'prod_t_shirt',
        descriptionKey: 'prod_t_shirt_desc',
        price: 32.99,
        imageSrc: '/images/products/vintage-tshirt.png',
        images: ['/images/products/vintage-tshirt.png', '/images/categories/t-shirts.png'],
        categoryKey: 'T-Shirts',
        createdAt: '2024-02-20',
        minimumOrder: 10,
        sizes: ['S', 'M', 'L', 'XL']
    },
    {
        id: '7',
        slug: 'winter-hoodie',
        nameKey: 'prod_hoodie',
        descriptionKey: 'prod_hoodie_desc',
        price: 64.99,
        imageSrc: '/images/products/winter-hoodie.png',
        images: ['/images/products/winter-hoodie.png', '/images/categories/sweatshirts.png'],
        categoryKey: 'Sweatshirts',
        createdAt: '2024-02-22',
        minimumOrder: 5,
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
    },
    {
        id: '8',
        slug: 'lifestyle-tote',
        nameKey: 'prod_tote',
        descriptionKey: 'prod_tote_desc',
        price: 24.99,
        imageSrc: '/images/products/lifestyle-tote.png',
        images: ['/images/products/lifestyle-tote.png', '/images/categories/bags.png'],
        categoryKey: 'Bags',
        createdAt: '2024-02-23',
        minimumOrder: 50,
        sizes: ['One Size']
    },
];

export const CATEGORIES = [
    { key: 'All', name: 'All Products', nameKey: '', imageSrc: '/images/categories/all-products.png' },
    { key: 'T-Shirts', name: 'T-Shirts', nameKey: 'cat_t_shirts', imageSrc: '/images/categories/t-shirts.png' },
    { key: 'Sweatshirts', name: 'Sweatshirts', nameKey: 'cat_sweatshirts', imageSrc: '/images/categories/sweatshirts.png' },
    { key: 'Hats', name: 'Hats', nameKey: 'cat_hats', imageSrc: '/images/categories/hats.png' },
    { key: 'Jackets & Vests', name: 'Jackets & Vests', nameKey: 'cat_jackets_vests', imageSrc: '/images/categories/jackets-vests.png' },
    { key: 'Bags', name: 'Bags', nameKey: 'cat_bags', imageSrc: '/images/categories/bags.png' },
    { key: 'Drinkware', name: 'Drinkware', nameKey: 'cat_drinkware', imageSrc: '/images/categories/drinkware.png' },
    { key: 'Polos', name: 'Polos', nameKey: 'cat_polos', imageSrc: '/images/categories/polos-business-wear.png' },
    { key: 'Workwear', name: 'Workwear', nameKey: 'cat_workwear', imageSrc: '/images/categories/workwear-uniforms.png' },
    { key: 'Office', name: 'Office Supplies', nameKey: 'cat_office', imageSrc: '/images/categories/office-supplies.png' },
    { key: 'Tech', name: 'Technology', nameKey: 'cat_tech', imageSrc: '/images/categories/technology.png' },
    { key: 'Signage', name: 'Signage', nameKey: 'cat_signage', imageSrc: '/images/categories/trade-show-signage.png' },
    { key: 'Activewear', name: 'Activewear', nameKey: 'cat_activewear', imageSrc: '/images/categories/activewear.png' },
];
