"use client";

import React, { useState, useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import GrafyEditor from '@/components/GrafyEditor/GrafyEditor';
import { useAuth } from '@/context/AuthContext';
import { useLanguage } from '@/context/LanguageContext';
import { db, auth, storage, processDesignImages } from '@/lib/firebase';
import { doc, getDoc, updateDoc, serverTimestamp } from 'firebase/firestore';
import { ref, uploadString, getDownloadURL } from 'firebase/storage';
import { Loader2 } from 'lucide-react';

export default function EditProductPage() {
    const { user } = useAuth();
    const { locale } = useLanguage();
    const router = useRouter();
    const params = useParams();
    const id = params?.id as string;
    
    const [initialData, setInitialData] = useState<any>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [isSaving, setIsSaving] = useState(false);

    useEffect(() => {
        const fetchCreation = async () => {
            if (!user || !id) return;
            try {
                const tenantId = auth.tenantId || 'default';
                const docRef = doc(db, 'GrafyShop', tenantId, 'products', id);
                const docSnap = await getDoc(docRef);
                
                if (docSnap.exists()) {
                    setInitialData(docSnap.data());
                } else {
                    router.push('/dashboard');
                }
            } catch (err) {
                console.error("Error fetching product:", err);
                router.push('/dashboard');
            } finally {
                setIsLoading(false);
            }
        };

        if (user && id) fetchCreation();
    }, [user, id, router]);

    const handleSave = async (data: any, thumbnail: string, mainImageOverride?: string | null) => {
        if (!user || !id) return;
        setIsSaving(true);
        try {
            const tenantId = auth.tenantId || 'default';
            
            // 0. Process and upload any new Base64 images
            const { processedSides, processedGallery, processedMainImage } = await processDesignImages(
                data.sides, 
                tenantId, 
                user.uid, 
                id,
                data.imageGallery,
                mainImageOverride
            );

            // 1. ALWAYS Update the auto-generated design preview in Storage (Base64)
            // This ensures "Generate new preview when saving after edit" is fulfilled.
            const previewRef = ref(storage, `GrafyShop/${tenantId}/products/${id}/preview.png`);
            const uploadResult = await uploadString(previewRef, thumbnail, 'data_url');
            const autoGeneratedURL = await getDownloadURL(uploadResult.ref);

            // 1b. Determine final Firestore thumbnail: Custom Main Image > Auto-generated
            const finalDocThumbnail = processedMainImage || autoGeneratedURL;

            // 1c. Upload/Update JSON configuration to Storage
            const configRef = ref(storage, `GrafyShop/${tenantId}/products/${id}/config.json`);
            const configData = JSON.stringify({
                sides: processedSides,
                imageGallery: processedGallery,
                activeColorId: data.activeColorId,
                activeSideId: data.activeSideId,
                productName: data.productName,
                productPrice: data.productPrice,
                mainImage: processedMainImage,
                userId: user.uid,
                tenantId: tenantId,
                updatedAt: new Date().toISOString()
            }, null, 2);
            await uploadString(configRef, configData, 'raw', { contentType: 'application/json' });

            // 2. Update Firestore
            await updateDoc(doc(db, 'GrafyShop', tenantId, 'products', id), {
                name: data.productName,
                productName: data.productName,
                productPrice: data.productPrice || '0.00',
                sides: processedSides,
                imageGallery: processedGallery,
                mainImage: processedMainImage,
                activeColorId: data.activeColorId,
                activeSideId: data.activeSideId,
                thumbnail: finalDocThumbnail,
                updatedAt: serverTimestamp()
            });

            router.push('/dashboard');
        } catch (err) {
            console.error("Error updating creation:", err);
            alert("Failed to update design.");
        } finally {
            setIsSaving(false);
        }
    };

    if (isLoading) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-[#FDFDFD]">
                <div className="flex flex-col items-center gap-4">
                    <Loader2 className="w-8 h-8 animate-spin text-black" />
                    <p className="text-[10px] font-black uppercase tracking-widest text-gray-400">Loading your workspace...</p>
                </div>
            </div>
        );
    }

    return (
        <div className="h-screen overflow-hidden">
            <GrafyEditor 
                initialData={initialData} 
                onSave={handleSave} 
                isSaving={isSaving} 
            />
        </div>
    );
}
