"use client";

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import GrafyEditor from '@/components/GrafyEditor/GrafyEditor';
import { useAuth } from '@/context/AuthContext';
import { useLanguage } from '@/context/LanguageContext';
import { db, auth, storage, processDesignImages } from '@/lib/firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { ref, uploadString, getDownloadURL } from 'firebase/storage';

export default function NewProductPage() {
    const { user } = useAuth();
    const { locale } = useLanguage();
    const router = useRouter();
    const [isSaving, setIsSaving] = useState(false);

    const handleSave = async (data: any, thumbnail: string, mainImageOverride?: string | null) => {
        if (!user) return;
        setIsSaving(true);
        try {
            const tenantId = auth.tenantId || 'default';
            
            // 0. CREATE A TEMPORARY ID FOR ASSETS
            const tempId = `prod-${Date.now()}`;

            // 1. Process and upload all Base64 images
            const { processedSides, processedGallery, processedMainImage } = await processDesignImages(
                data.sides, 
                tenantId, 
                user.uid, 
                tempId,
                data.imageGallery,
                mainImageOverride
            );

            // 2. Save document to Firestore with optimized data
            const docRef = await addDoc(collection(db, 'GrafyShop', tenantId, 'products'), {
                userId: user.uid,
                name: data.productName,
                productName: data.productName,
                productPrice: data.productPrice || '0.00',
                sides: processedSides,
                imageGallery: processedGallery,
                mainImage: processedMainImage,
                activeColorId: data.activeColorId,
                activeSideId: data.activeSideId,
                createdAt: serverTimestamp(),
                updatedAt: serverTimestamp(),
                tenantId: tenantId
            });

            // 3. ALWAYS Upload the auto-generated design preview to Storage (Base64)
            const previewRef = ref(storage, `GrafyShop/${tenantId}/products/${docRef.id}/preview.png`);
            const uploadResult = await uploadString(previewRef, thumbnail, 'data_url');
            const autoGeneratedURL = await getDownloadURL(uploadResult.ref);

            // 3b. Determine final Firestore thumbnail: Custom Main Image > Auto-generated
            const finalDocThumbnail = processedMainImage || autoGeneratedURL;

            // 4. Upload JSON configuration to Storage (with optimized URLs)
            const configRef = ref(storage, `GrafyShop/${tenantId}/products/${docRef.id}/config.json`);
            const configData = JSON.stringify({
                name: data.productName,
                productName: data.productName,
                productPrice: data.productPrice,
                sides: processedSides,
                imageGallery: processedGallery,
                mainImage: processedMainImage,
                activeColorId: data.activeColorId,
                activeSideId: data.activeSideId,
                userId: user.uid,
                tenantId: tenantId,
                updatedAt: new Date().toISOString()
            }, null, 2);
            await uploadString(configRef, configData, 'raw', { contentType: 'application/json' });

            // Update Doc with final thumbnail and mainImage reference
            const { updateDoc, doc } = await import('firebase/firestore');
            await updateDoc(doc(db, 'GrafyShop', tenantId, 'products', docRef.id), {
                thumbnail: finalDocThumbnail
            });

            router.push('/dashboard');
        } catch (err) {
            console.error("Error saving creation:", err);
            alert("Failed to save design.");
        } finally {
            setIsSaving(false);
        }
    };

    return (
        <div className="h-screen overflow-hidden">
            <GrafyEditor onSave={handleSave} isSaving={isSaving} />
        </div>
    );
}
