import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies, headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ConditionalLayout from "@/components/ConditionalLayout";
import { LanguageProvider } from "@/context/LanguageContext";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const headerStore = await headers();

  let initialLocale: 'en' | 'fr' = 'en';

  const savedLocale = cookieStore.get('NEXT_LOCALE')?.value;
  if (savedLocale === 'en' || savedLocale === 'fr') {
    initialLocale = savedLocale;
  } else {
    const acceptLanguage = headerStore.get('accept-language');
    if (acceptLanguage?.startsWith('fr')) {
      initialLocale = 'fr';
    }
  }

  return (
    <html lang={initialLocale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider initialLocale={initialLocale}>
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
        </LanguageProvider>
      </body>
    </html>
  );
}
