"use client";

import React, { createContext, useContext, useEffect, useState } from 'react';

type Locale = 'en' | 'fr';

interface LanguageContextType {
    locale: Locale;
    setLocale: (locale: Locale) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Locale, Record<string, string>> = {
    en: {
        nav_home: "Home",
        nav_shop: "Shop",
        nav_categories: "Categories",
        nav_about: "About",
        hero_title: "Bring Your Brand To Every Surface",
        hero_subtitle: "Professional quality prints for businesses, events, and individuals. High-quality apparel and accessories, customized just for you.",
        hero_cta: "Start Creating",
        group_cta: "Inquire for Groups",
        user_welcome: "Welcome to GrafyShop",
        user_login: "Sign In",
        user_signup: "Create Account",
        search_placeholder: "Search categories...",
        search_no_results: "No categories found.",
        search_type_category: "Category",
        search_type_product: "Product",
        prod_t_shirt: "Classic Heavy Cotton T-Shirt",
        prod_hoodie: "Premium Pullover Hoodie",
        prod_mug: "Custom Ceramic Mug",
        prod_tote: "Eco-Friendly Tote Bag",
        prod_notebook: "Signature Hardcover Notebook",
        prod_tumbler: "Branded Stainless Tumbler",
        prod_t_shirt_desc: "Premium weight cotton t-shirt with a classic fit. Perfect for high-quality branding and long-lasting wear.",
        prod_hoodie_desc: "Soft and durable pullover hoodie with a modern fit. Features reinforced seams and a double-lined hood.",
        prod_mug_desc: "Standard 11oz ceramic mug with a smooth finish. Ideal for vibrant full-color printing.",
        prod_tote_desc: "100% organic cotton tote bag with reinforced handles. Sustainable and practical for everyday use.",
        prod_tumbler_desc: "Double-walled stainless steel tumbler that keeps drinks hot or cold for hours. Sleek design for a premium look.",
        product_min_order: "Minimum Order: {count} units",
        add_to_cart: "Add to Cart",
        personalize_design: "Personalize Design",
        personalize_now: "Personalize Now",
        quantity: "Quantity",
        total_quantity: "Total Quantity",
        total_price: "Total Price",
        select_sizes_desc: "Specify the quantity for each size. The total must be at least {count} units.",
        min_order_not_met: "Total quantity must be at least {count} units.",
        size: "Size",
        cat_t_shirts: "T-shirts",
        cat_sweatshirts: "Sweatshirts",
        cat_hats: "Hats",
        cat_jackets_vests: "Jackets & Vests",
        cat_bags: "Bags",
        cat_drinkware: "Drinkware",
        cat_polos: "Polos & Business Wear",
        cat_workwear: "Workwear and Uniforms",
        cat_office: "Office Supplies",
        cat_tech: "Technology",
        cat_signage: "Trade Show & Signage",
        cat_activewear: "Activewear",
        cat_section_title: "Custom T-shirts & Promotional Products for Your Group",
        hero_main_title: "Design. Print. Deliver.",
        hero_main_subtitle: "Your complete web-to-print solution for custom apparel, business stationery, and promotional products. Fast, simple, and professional.",
        hero_main_cta: "Create Your Project",
        steps_title: "How It Works",
        step_1_title: "Choose Product",
        step_1_desc: "Select from our premium catalog of apparel and branding surfaces.",
        step_2_title: "Add Your Design",
        step_2_desc: "Upload your artwork or work with our templates to create your vision.",
        step_3_title: "We Print & Deliver",
        step_3_desc: "Expert printing and fast shipping directly to your business or home.",
        arrivals_title: "New Arrivals Are Here",
        arrivals_desc: "Gear up for the season with fresh picks from the brands you love. From cozy layers to cool accessories, we're always adding more!",
        arrivals_cta: "Shop Now",
        footer_support: "Support",
        footer_contact: "Contact Us",
        footer_shipping: "Shipping Info",
        footer_faq: "FAQs",
        footer_privacy: "Privacy Policy",
        footer_terms: "Terms of Service",
        footer_phone: "Phone",
        footer_email: "Email",
        footer_rights: "All rights reserved.",
        footer_description: "Your complete web-to-print solution for custom apparel, business stationery, and promotional products.",
        about_hero_title: "We bring your brand to life",
        about_hero_subtitle: "At GrafyShop, we believe every surface is a potential canvas for your brand. We provide premium quality custom prints for everyone.",
        about_story_title: "Our Story",
        about_story_p1: "Founded with a passion for high-quality printing, GrafyShop has evolved into a leading web-to-print platform serving businesses and individuals worldwide.",
        about_story_p2: "We combine cutting-edge technology with traditional craftsmanship to deliver products that truly represent your vision.",
        about_values_title: "Our Values",
        about_value_1_title: "Quality First",
        about_value_1_desc: "We never compromise on materials or print quality.",
        about_value_2_title: "Lightning Speed",
        about_value_2_desc: "Efficient processes ensuring your brand reaches customers fast.",
        about_value_3_title: "Always Inventing",
        about_value_3_desc: "Constantly updating our techniques and product catalog.",
        cart_title: "Your Cart",
        cart_empty: "Your cart is empty",
        cart_continue_shopping: "Continue Shopping",
        cart_summary: "Order Summary",
        cart_subtotal: "Subtotal",
        cart_shipping: "Shipping",
        cart_tax: "Estimated Tax",
        cart_total: "Total",
        cart_checkout: "Proceed to Checkout",
        cart_remove: "Remove",
        cart_free: "Free",
        cart_items: "items",
        fav_title: "My Favorites",
        fav_empty: "No favorites yet",
        fav_description: "Save items you love to find them easily later.",
        fav_count: "items saved",
        auth_login_title: "Welcome Back",
        auth_login_subtitle: "Sign in to access your custom projects and saved items.",
        auth_register_title: "Join GrafyShop",
        auth_register_subtitle: "Create an account to start designing and saving your favorites.",
        auth_email: "Email Address",
        auth_password: "Password",
        auth_forgot_password: "Forgot Password?",
        auth_no_account: "Don't have an account?",
        auth_has_account: "Already have an account?",
        auth_google_login: "Continue with Google",
        auth_or: "or",
        contact_title: "Get in Touch",
        contact_subtitle: "Have a project in mind or need help? Reach out to our expert team.",
        contact_form_name: "Full Name",
        contact_form_email: "Email Address",
        contact_form_subject: "Subject",
        contact_form_message: "Message",
        contact_form_send: "Send Message",
        contact_form_success: "Thank you! Your message has been sent.",
        contact_info_title: "Contact Information",
        contact_info_desc: "Prefer direct communication? Here's how you can find us.",
        faq_title: "Frequently Asked Questions",
        faq_subtitle: "Everything you need to know about our products, printing, and shipping.",
        faq_q1_title: "General",
        faq_q1: "How does the custom printing work?",
        faq_a1: "Simply choose a product, upload your design, and our experts will handle the rest with professional quality checks.",
        faq_q2_title: "Shipping",
        faq_q2: "What is the average shipping time?",
        faq_a2: "Standard production takes 5-7 days, with shipping taking an additional 3-5 days depending on your location.",
        faq_q3_title: "Ordering",
        faq_q3: "Can I order a single custom unit?",
        faq_a3: "While most items have a minimum order requirement for quality consistency, some select items are available for single-unit orders.",
        shipping_title: "Shipping Information",
        shipping_intro: "We deliver your custom products with care and speed. Here is everything you need to know about our logistics.",
        shipping_section_1_title: "Production Times",
        shipping_section_1_desc: "All products at GrafyShop are made to order. Our standard production time is 5-7 business days. This allows us to ensure the highest quality for your personalized designs.",
        shipping_section_2_title: "Delivery Estimates",
        shipping_section_2_desc: "Once production is complete, domestic shipping typically takes 2-3 business days. International delivery varies by location but generally arrives within 5-10 business days.",
        shipping_section_3_title: "Tracking Your Order",
        shipping_section_3_desc: "You will receive a tracking link via email as soon as your order leaves our studio. You can follow your package's journey in real-time.",
        privacy_title: "Privacy Policy",
        privacy_intro: "Your trust is our most valuable asset. We are committed to protecting your personal data and being transparent about how we use it.",
        privacy_section_1_title: "Information We Collect",
        privacy_section_1_desc: "We collect information you provide directly to us: name, email, shipping address, and payment details. We also collect design files you upload for customization.",
        privacy_section_2_title: "How We Use Data",
        privacy_section_2_desc: "Your data is used solely to process your orders, communicate with you about your projects, and provide a personalized shopping experience.",
        privacy_section_3_title: "Data Security",
        privacy_section_3_desc: "We use industry-standard encryption and secure servers to protect your information because your security is our priority.",
        terms_title: "Terms of Use",
        terms_intro: "Welcome to GrafyShop. By accessing our platform, you agree to these terms. Please read them carefully.",
        terms_section_1_title: "Account Responsibility",
        terms_section_1_desc: "You are responsible for maintaining the confidentiality of your account and for all activities that occur under your account.",
        terms_section_2_title: "Design Guidelines",
        terms_section_2_desc: "When uploading designs, you confirm that you own the rights to the artwork. We reserve the right to refuse designs that violate intellectual property or community standards.",
        terms_section_3_title: "Sales & Refunds",
        terms_section_3_desc: "Since each item is custom-made, all sales are final once production begins. Refunds are only issued for manufacturing defects or shipping damage.",
        account_title: "My Account",
        account_orders: "Order History",
        account_profile: "Profile Settings",
        order_number: "Order #",
        order_date: "Date",
        order_total: "Total",
        order_status: "Status",
        status_processing: "Processing",
        status_printing: "Printing",
        status_shipped: "Shipped",
        status_delivered: "Delivered",
        order_view_details: "View Details",
        order_details_title: "Order Details",
        order_info_shipping_address: "Shipping Address",
        order_info_billing_address: "Billing Address",
        order_info_payment_method: "Payment Method",
        order_items_title: "Items in this order",
        order_summary_subtotal: "Subtotal",
        order_summary_shipping: "Shipping",
        order_summary_tax: "Estimated Tax",
        order_back_to_list: "Back to Account",
    },
    fr: {
        nav_home: "Accueil",
        nav_shop: "Boutique",
        nav_categories: "Catégories",
        nav_about: "À propos",
        hero_title: "Donnez vie à votre marque sur tous supports",
        hero_subtitle: "Impressions de qualité professionnelle pour entreprises, événements et particuliers. Vêtements et accessoires de haute qualité, personnalisés pour vous.",
        hero_cta: "Commencer à créer",
        group_cta: "Demande pour groupe",
        user_welcome: "Bienvenue sur GrafyShop",
        user_login: "Se connecter",
        user_signup: "Créer un compte",
        search_placeholder: "Rechercher...",
        search_no_results: "Aucun résultat trouvé.",
        search_type_category: "Catégorie",
        search_type_product: "Produit",
        prod_t_shirt: "T-shirt classique en coton",
        prod_hoodie: "Sweat à capuche premium",
        prod_mug: "Mug en céramique personnalisé",
        prod_tote: "Sac en toile éco-responsable",
        prod_notebook: "Carnet de notes signature",
        prod_tumbler: "Gobelet isotherme marqué",
        prod_t_shirt_desc: "T-shirt en coton de qualité supérieure avec une coupe classique. Parfait pour un marquage de haute qualité.",
        prod_hoodie_desc: "Sweat à capuche doux et durable avec une coupe moderne. Comprend des coutures renforcées.",
        prod_mug_desc: "Mug en céramique standard de 11 oz avec une finition lisse. Idéal pour une impression éclatante.",
        prod_tote_desc: "Sac en toile 100% coton bio avec poignées renforcées. Durable et pratique au quotidien.",
        prod_tumbler_desc: "Gobelet en acier inoxydable à double paroi qui garde les boissons chaudes ou froides. Design épuré.",
        product_min_order: "Commande minimum : {count} unités",
        add_to_cart: "Ajouter au panier",
        personalize_design: "Personnaliser le Design",
        personalize_now: "Personnaliser Maintenant",
        quantity: "Quantité",
        total_quantity: "Quantité Totale",
        total_price: "Prix Total",
        select_sizes_desc: "Spécifiez la quantité pour chaque taille. Le total doit être d'au moins {count} unités.",
        min_order_not_met: "La quantité totale doit être d'au moins {count} unités.",
        size: "Taille",
        cat_t_shirts: "T-shirts",
        cat_sweatshirts: "Sweat-shirts",
        cat_hats: "Chapeaux",
        cat_jackets_vests: "Vestes et Gilets",
        cat_bags: "Sacs",
        cat_drinkware: "Articles de boisson",
        cat_polos: "Polos et Tenues de ville",
        cat_workwear: "Vêtements de travail",
        cat_office: "Fournitures de bureau",
        cat_tech: "Technologie",
        cat_signage: "Signalétique Salon",
        cat_activewear: "Vêtements de sport",
        cat_section_title: "T-shirts personnalisés et objets publicitaires pour votre groupe",
        hero_main_title: "Concevez. Imprimez. Livrez.",
        hero_main_subtitle: "Votre solution web-to-print complète pour vêtements personnalisés, papeterie d'entreprise et objets publicitaires. Rapide, simple et professionnel.",
        hero_main_cta: "Créer votre projet",
        steps_title: "Comment ça marche",
        step_1_title: "Choisissez votre produit",
        step_1_desc: "Sélectionnez parmi notre catalogue premium de vêtements et supports.",
        step_2_title: "Ajoutez votre design",
        step_2_desc: "Téléchargez votre logo ou utilisez nos modèles pour créer votre vision.",
        step_3_title: "On imprime et on livre",
        step_3_desc: "Impression experte et expédition rapide directement chez vous.",
        arrivals_title: "Les nouveautés sont arrivées",
        arrivals_desc: "Préparez-vous pour la saison avec les nouveautés de vos marques préférées. Des vêtements confortables aux accessoires tendance, nous en ajoutons sans cesse !",
        arrivals_cta: "Acheter maintenant",
        footer_support: "Support",
        footer_contact: "Contactez-nous",
        footer_shipping: "Livraison",
        footer_faq: "FAQ",
        footer_privacy: "Politique de confidentialité",
        footer_terms: "Conditions d'utilisation",
        footer_phone: "Téléphone",
        footer_email: "Email",
        footer_rights: "Tous droits réservés.",
        footer_description: "Votre solution web-to-print complète pour vêtements personnalisés, papeterie d'entreprise et objets publicitaires.",
        about_hero_title: "Nous donnons vie à votre marque",
        about_hero_subtitle: "Chez GrafyShop, we believe every surface is a potential canvas for your brand. We provide premium quality custom prints for everyone.",
        about_story_title: "Notre Histoire",
        about_story_p1: "Fondée avec une passion pour l'impression de haute qualité, GrafyShop est devenue une plateforme web-to-print de premier plan au service des entreprises et des particuliers du monde entier.",
        about_story_p2: "Nous combinons une technologie de pointe avec un savoir-faire traditionnel pour livrer des produits qui représentent vraiment votre vision.",
        about_values_title: "Nos Valeurs",
        about_value_1_title: "La Qualité d'abord",
        about_value_1_desc: "Nous ne faisons jamais de compromis sur les matériaux ou la qualité d'impression.",
        about_value_2_title: "Vitesse Éclair",
        about_value_2_desc: "Des processus efficaces garantissant que votre marque atteigne ses clients rapidement.",
        about_value_3_title: "Toujours Inventif",
        about_value_3_desc: "Mise à jour constante de nos techniques et de notre catalogue de produits.",
        cart_title: "Votre Panier",
        cart_empty: "Votre panier est vide",
        cart_continue_shopping: "Continuer les achats",
        cart_summary: "Résumé de la commande",
        cart_subtotal: "Sous-total",
        cart_shipping: "Livraison",
        cart_tax: "Taxe estimée",
        cart_total: "Total",
        cart_checkout: "Passer à la caisse",
        cart_remove: "Supprimer",
        cart_free: "Gratuit",
        cart_items: "articles",
        fav_title: "Mes Favoris",
        fav_empty: "Aucun favori pour l'instant",
        fav_description: "Enregistrez les articles que vous aimez pour les retrouver facilement plus tard.",
        fav_count: "articles enregistrés",
        auth_login_title: "Bon retour",
        auth_login_subtitle: "Connectez-nous pour accéder à vos projets personnalisés et articles enregistrés.",
        auth_register_title: "Rejoignez GrafyShop",
        auth_register_subtitle: "Créez un compte pour commencer à concevoir et enregistrer vos favoris.",
        auth_email: "Adresse Email",
        auth_password: "Mot de passe",
        auth_forgot_password: "Mot de passe oublié ?",
        auth_no_account: "Vous n'avez pas de compte ?",
        auth_has_account: "Vous avez déjà un compte ?",
        auth_google_login: "Continuer avec Google",
        auth_or: "ou",
        contact_title: "Contactez-nous",
        contact_subtitle: "Vous avez un projet en tête ou besoin d'aide ? Contactez notre équipe d'experts.",
        contact_form_name: "Nom complet",
        contact_form_email: "Adresse email",
        contact_form_subject: "Sujet",
        contact_form_message: "Message",
        contact_form_send: "Envoyer le message",
        contact_form_success: "Merci ! Votre message a été envoyé.",
        contact_info_title: "Informations de contact",
        contact_info_desc: "Vous préférez une communication directe ? Voici comment nous trouver.",
        faq_title: "Foire aux questions",
        faq_subtitle: "Tout ce que vous devez savoir sur nos produits, l'impression et la livraison.",
        faq_q1_title: "Général",
        faq_q1: "Comment fonctionne l'impression personnalisée ?",
        faq_a1: "Choisissez simplement un produit, téléchargez votre logo, et nos experts s'occupent du reste avec un contrôle qualité professionnel.",
        faq_q2_title: "Livraison",
        faq_q2: "Quel est le délai de livraison moyen ?",
        faq_a2: "La production standard prend 5 à 7 jours, et la livraison 3 à 5 jours supplémentaires selon votre emplacement.",
        faq_q3_title: "Commande",
        faq_q3: "Puis-je commander une seule unité personnalisée ?",
        faq_a3: "Bien que la plupart des articles aient un minimum de commande, certains articles sélectionnés sont disponibles à l'unité.",
        shipping_title: "Informations de livraison",
        shipping_intro: "Nous livrons vos produits personnalisés avec soin et rapidité. Voici tout ce que vous devez savoir sur notre logistique.",
        shipping_section_1_title: "Délais de production",
        shipping_section_1_desc: "Tous les produits de GrafyShop sont fabriqués sur commande. Notre délai de production standard est de 5 à 7 jours ouvrables pour garantir la meilleure qualité.",
        shipping_section_2_title: "Délais de livraison",
        shipping_section_2_desc: "Une fois la production terminée, la livraison nationale prend généralement 2-3 jours ouvrables. L'international varie de 5 à 10 jours ouvrables selon la destination.",
        shipping_section_3_title: "Suivi de commande",
        shipping_section_3_desc: "Vous recevrez un lien de suivi par e-mail dès que votre commande quitte notre atelier. Vous pourrez suivre le trajet de votre colis en temps réel.",
        privacy_title: "Politique de confidentialité",
        privacy_intro: "Votre confiance est notre atout le plus précieux. Nous nous engageons à protéger vos données personnelles et à être transparents sur leur utilisation.",
        privacy_section_1_title: "Informations collectées",
        privacy_section_1_desc: "Nous collectons les informations que vous nous fournissez : nom, e-mail, adresse de livraison et détails de paiement, ainsi que vos fichiers de conception.",
        privacy_section_2_title: "Utilisation des données",
        privacy_section_2_desc: "Vos données sont utilisées exclusivement pour traiter vos commandes, communiquer sur vos projets et vous offrir une expérience personnalisée.",
        privacy_section_3_title: "Sécurité des données",
        privacy_section_3_desc: "Nous utilisons un cryptage standard et des serveurs sécurisés pour protéger vos informations, car votre sécurité est notre priorité.",
        terms_title: "Conditions d'utilisation",
        terms_intro: "Bienvenue sur GrafyShop. En accédant à notre plateforme, vous acceptez ces conditions. Veuillez les lire attentivement.",
        terms_section_1_title: "Responsabilité du compte",
        terms_section_1_desc: "Vous êtes responsable du maintien de la confidentialité de votre compte et de toutes les activités qui se déroulent sous celui-ci.",
        terms_section_2_title: "Règles de conception",
        terms_section_2_desc: "En téléchargeant des designs, vous confirmez en posséder les droits. Nous nous réservons le droit de refuser tout design enfreignant la propriété intellectuelle.",
        terms_section_3_title: "Ventes et remboursements",
        terms_section_3_desc: "Chaque article étant personnalisé, toutes les ventes sont finales dès le début de la production. Les remboursements ne concernent que les défauts de fabrication.",
        account_title: "Mon Compte",
        account_orders: "Historique des commandes",
        account_profile: "Paramètres du profil",
        order_number: "Commande #",
        order_date: "Date",
        order_total: "Total",
        order_status: "Statut",
        status_processing: "En cours",
        status_printing: "Impression",
        status_shipped: "Expédié",
        status_delivered: "Livré",
        order_view_details: "Voir les détails",
        order_details_title: "Détails de la commande",
        order_info_shipping_address: "Adresse de livraison",
        order_info_billing_address: "Adresse de facturation",
        order_info_payment_method: "Mode de paiement",
        order_items_title: "Articles dans cette commande",
        order_summary_subtotal: "Sous-total",
        order_summary_shipping: "Livraison",
        order_summary_tax: "Taxe estimée",
        order_back_to_list: "Retour au compte",
    },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode; initialLocale?: Locale }> = ({
    children,
    initialLocale = 'en'
}) => {
    const [locale, setLocaleState] = useState<Locale>(initialLocale);

    useEffect(() => {
        // Sync state if initialLocale changes (e.g. server-side detection changes)
        if (initialLocale && initialLocale !== locale) {
            setLocaleState(initialLocale);
        }
    }, [initialLocale]);

    const setLocale = (newLocale: Locale) => {
        setLocaleState(newLocale);
        // Set cookie for server-side detection on next request
        document.cookie = `NEXT_LOCALE=${newLocale}; path=/; max-age=31536000`; // 1 year
    };

    const t = (key: string) => {
        return translations[locale][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ locale, setLocale, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
